In [8]:
import os
import time
import pandas as pd
from process_results import concat_stats_files

In [9]:
HOME_DIR = os.path.expanduser('~/')
script_path = '/home/lantro/Documents/Algo/Strategies/Using Pandas/Momentum/Multiple Timeframes 2.2.1'
cached_data = script_path+'/'+'cached_data'
stats_data = script_path+'/'+'stats'
data_folder = f'{HOME_DIR}/Documents/Algo/Data'
ticker_folder = f'{data_folder}/Tickers/Nasdaq-100'
current_date = time.strftime("%Y.%m.%d.%H%M%S")
param_dict = {'rebal_int': 2, 'stop_type': 'indiv', 'stop': 0, 'qty_long': 43, 'qty_med': 20, 'qty_short': 10, 'SMA_L': 139, 'SMA_S': 9, 'rolling_l': 34, 'rolling_m': 16, 'rolling_s': 8}
#tested_combos_df = pd.read_csv(f'{stats_data}/M_nasdaq100_stats_2023.06.11.114948.csv', index_col=None, header=0)

We need to find if any rows in tested_combos_df contain our proposed parameter combos.
https://www.appsdeveloperblog.com/pandas-how-to-select-rows-based-on-column-values/

In [16]:
# Get dataframe of all stats from previous backtests
all_stats_df = concat_stats_files() # This function returns stats from previous backtests
param_columns = [column for column in all_stats_df.columns if column in param_dict] # Get list of parameters we're testing
tested_combos_df = all_stats_df.loc[:,param_columns][0:5] # For our testing, we'll take first few rows for tested_combos_df
proposed_combos_df = all_stats_df.loc[:,param_columns][3:7] # For our testing, we'll take next few rows with some overlap for proposed_combos_df
tested_combos_df.head()

Total rows imported:  169

,rebal_int,qty_long,qty_med,qty_short,SMA_S,SMA_L,stop,rolling_l,rolling_m,rolling_s
0,3,28,20,10,9,139,0,34,16,8
1,3,29,20,10,9,139,0,34,16,8
2,3,30,20,10,9,139,0,34,16,8
3,3,32,20,10,9,139,0,34,16,8
4,3,27,20,10,9,139,0,34,16,8

In [ ]:
# NEW WAY: compare tested_combos_df with proposed_combos_df and keep rows that only exist in proposed_combo_df

In [13]:
# OLD WAY
# Create a dict of proposed parameter combo, which we can convert into df for comparison with
# Check to see if we've tested this combination of parameters before appending to combo test list
query_keys_values = [] # List to store proposed parameter combos to create query
combo_dict = {} # Create a dict of combo, value pairs to add to tested_combos_df
params = tested_combos_df.columns
for param in params:
    if param in param in param_dict: # Param exists in stats and params dict
        query_keys_values.append(f'{param}=={param_dict[param]}')
        combo_dict[param] = param_dict[param]
#query_str = 'rebal_int==3 and qty_long==43 and qty_med==20 and qty_short==10 and SMA_S==9 and SMA_L==139 and stop==0 and rolling_l==34 and rolling_m==16 and rolling_s==8'
query_str = ((' and ').join(query_keys_values)) # Create query string from our proposed parameter combos to query \
# tested_combos_df to see if we've tested before
print(f'query_str: {query_str}')
matched_rows = tested_combos_df.query(query_str)
print(f'matched_rows: {len(matched_rows)}\n')
if len(matched_rows) == 0: # If we don't find proposed combo in tested_combos_df, we'll add so we don't test again during this run
    #print(f'combo_dict: {combo_dict}')
    print(f'Param combo not used before, adding to combos to test:\n{combo_dict}')
    combos_df = pd.DataFrame(data=combo_dict, index=[0])
    tested_combos_df = pd.concat([tested_combos_df, combos_df], ignore_index=True).drop_duplicates(keep='first')
else:
    print(f'Param combo already tested:\n{combo_dict}')

query_str: rebal_int==2 and qty_long==43 and qty_med==20 and qty_short==10 and SMA_S==9 and SMA_L==139 and stop==0 and rolling_l==34 and rolling_m==16 and rolling_s==8
matched_rows: 1

Param combo already tested:
{'rebal_int': 2, 'qty_long': 43, 'qty_med': 20, 'qty_short': 10, 'SMA_S': 9, 'SMA_L': 139, 'stop': 0, 'rolling_l': 34, 'rolling_m': 16, 'rolling_s': 8}

In [15]:
tested_combos_df.head(10)

,rebal_int,qty_long,qty_med,qty_short,SMA_S,SMA_L,stop,rolling_l,rolling_m,rolling_s
0,3,28,20,10,9,139,0,34,16,8
1,3,29,20,10,9,139,0,34,16,8
2,3,30,20,10,9,139,0,34,16,8
3,3,32,20,10,9,139,0,34,16,8
4,3,27,20,10,9,139,0,34,16,8
5,3,34,20,10,9,139,0,34,16,8
6,3,33,20,10,9,139,0,34,16,8
7,3,43,20,10,9,139,0,34,16,8
8,3,35,20,10,9,139,0,34,16,8
9,3,42,20,10,9,139,0,34,16,8