In [8]:
import os
import sys
import pandas as pd
import get_parameters, get_data, optimization, strategies, signals, risk_management, analysis

HOME_DIR = os.path.expanduser('~/')
sys.path.append(f"{HOME_DIR}/Documents/Algo/Stock Price DB/")
script_path = os.path.dirname('./')

In [9]:
all_stats_df = pd.read_csv(f'{script_path}/all_stats_df.csv')

In [10]:
all_stats_df.head()

,rebal_int,top_n,SMA_S,SMA_L,stop,rolling_l,rolling_m,rolling_s,tot_ret,cagr,sharpe,perf_score,max_dd,stats_file
0,1,"(25, 20, 1)",9,139,80,34,16,8,513.28,1.26,5.91,3033.48,-0.73,M_nasdaq100_stats_2023.06.02.190501.csv
1,1,"(25, 20, 1)",9,139,80,34,16,8,513.28,1.26,5.91,3033.48,-0.73,M_nasdaq100_stats_2023.06.02.192101.csv
2,1,"(25, 20, 5)",9,139,80,34,16,8,421.67,0.68,7.06,2976.99,-0.45,M_nasdaq100_stats_2023.06.03.140711.csv
3,1,"(25, 20, 5)",9,139,80,34,16,8,421.67,0.68,7.06,2976.99,-0.45,M_nasdaq100_stats_2023.06.03.141337.csv
4,3,"(25, 20, 1)",9,139,60,34,16,8,293.82,0.58,6.69,1965.66,-0.52,M_nasdaq100_stats_2023.06.04.133243.csv

In [18]:
corr = all_stats_df.loc[:,['tot_ret', 'sharpe', 'perf_score']].corr()
corr

             tot_ret    sharpe  perf_score
tot_ret     1.000000  0.183821    0.985080
sharpe      0.183821  1.000000    0.289065
perf_score  0.985080  0.289065    1.000000